### ISSUE TITLE
How do I update FMLRC2

### ISSUE THREAD

**Issue by cement-head** [HudsonAlpha/rust-fmlrc#20]
If I have installed FMLRC2 via the cargo/RUST method, how does one update the installation?

Do I simply type: 

`$ cargo install fmlrc`

TIA

**Comment by holtjma** [comment]
Yes, according to the cargo docs it will update if it detects a newer version: [https://doc.rust-lang.org/cargo/commands/cargo-install.html](https://doc.rust-lang.org/cargo/commands/cargo-install.html)
