### ISSUE TITLE
Question about replicates

### ISSUE THREAD

**Issue by majdabdul** [HudsonAlpha/rust-fmlrc#21]
Hello,

Thank you for providing this valuable tool. May I ask how to deal with biological replicates? I have three short-read RNA-seq biological replicates and three long-read biological replicates. How do I account for that when running fmlrc2? 

Thank you!

**Comment by holtjma** [comment]
I'm not sure I understand what you're asking.  Can you provide more details around the confusion with respect to fmlrc?  Are there multiple options you're trying to decide between?

**Comment by majdabdul** [comment]
> I'm not sure I understand what you're asking. Can you provide more details around the confusion with respect to fmlrc? Are there multiple options you're trying to decide between?

Thanks for responding, Matt. I have long-read sequencing and short-read sequencing data, with three biological replicates of each sample. I want to correct the long-reads with the short-read data, and want to use FMLRC for that. I'm kind of stuck in the first step, MSBWT Building, because I'm not sure how to take into account the three replicates. 

Say I run:
`gunzip -c reads.fq.gz | awk 'NR % 4 == 2' | sort | tr NT TN | ropebwt2 -LR | tr NT TN | fmlrc-convert /path/to/output/comp_msbwt.npy`

If I'm understanding correctly, reads.fq.gz is the file I want to correct with (i.e. the short-reads file). So do I do this step for each of the three replicates of the short-read data? Then I'll have three msbwt.npy. How does that work when running:

`fmlrc2 [OPTIONS] <comp_msbwt.npy> <uncorrected.fq.gz> <corrected_reads.fa>`?

I hope this makes the question clearer.

**Comment by holtjma** [comment]
You probably need to decide how you want your experiment to run.  I can think of two main options that depend on what you're trying to achieve:

1. If you want to show reproducibility or keep your replicates separate for w/e reason, you will likely need to pair your short reads and long reads.  This means you will correct long read set A with short read set A, B with B, and C with C.  This necessitates building three different MSBWTs, one for each set.  (Note, you could obviously extend this further depending on the nature of your experiment; e.g. pair A with B or C, B with A or C, and/or C with A or B)
2. If you just want to use all of the data possible, then you will need to merge your short read datasets prior to building the MSBWT.  The easiest way to do that is to just modify the first line to `gunzip -c readsA.fq.gz readsB.fq.gz readsC.fq.gz | ...` during construction so all three short read datasets are in one MSBWT.  Then you can run each long read datasets against the single MSBWT.

Does that help answer your question?

**Comment by majdabdul** [comment]
Yes, that's really helpful, thank you! I'm going with option 2.
