### ISSUE TITLE
"error: Found argument '21' which wasn't expected, or isn't valid in this context" When attempting FMLRC2 in Eukaryote Mode

### ISSUE THREAD

**Issue by jwalewski** [HudsonAlpha/rust-fmlrc#30]
Hello, while trying to run FMLRC2 in eukaryote mode inside of a shell script I keep getting an error relating to the fact that there are seemingly too many (3) values for k when 2 are expected:

Here's the command I'm running, which worked perfectly fine before specifying _k_:

```fmlrc2 –min_frac 0 -t $NUMPROCS -C $CACHE_SIZE −k 21 59 80 -- $MSBWTPATH$RESEQREADNAME$RESEQREAD_COV_MIN"Xv"$actual_RES_version_num"_msbwtindex.npy" $PACBIOREADPATH$PACBIOREADNAME$PACBIOREAD_COV_MIN"Xv"$actual_PB_version_num".fq.gz" $OUTPUTREADPATH$RESEQREADNAME$RESEQREAD_COV_MIN"Xv"$actual_RES_version_num"_"$PACBIOREADNAME$PACBIOREAD_COV_MIN"Xv"$actual_PB_version_num".fa"```

Any insight would be greatly appreciated!

**Comment by holtjma** [comment]
Assuming this is verbatim copied from your script, I think it is as simple as missing the double-dash and label for min_frac, e.g. `--min_dynamic_count` (or if you want abbreviated, `-f`).

**Comment by jwalewski** [comment]
That solved the issue, thanks!
