### ISSUE TITLE
error: Found argument '79' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by bsb2014** [HudsonAlpha/rust-fmlrc#31]
My CML is 
fmlrc2 −k 21 59 79 -- --min_dynamic_count 0  -v -t 42 -C 10  comp_msbwt.npy  polished.fasta  Polished.2.fa
The error is 
error: Found argument '79' which wasn't expected, or isn't valid in this context
I also tried the default K range and it worked well.

Any suggestions are appreciated.

**Comment by holtjma** [comment]
Hello,

There are a few things wrong with the above syntax:

1. the specific error you are encountering seems to be cause by a _different_ character that looks like hyphen, e.g.: you have "−k" and you should be using "-k"; I'm not sure what that character is, but it is not registering as a hyphen in the CLI
2. second, you do not need the "--" unless it is the end of your optional parameters.

If you try again, I believe you will find this this works:
```
fmlrc2 -k 21 59 79 --min_dynamic_count 0 -v -t 42 -C 10 comp_msbwt.npy polished.fasta Polished.2.fa
```

**Comment by bsb2014** [comment]
It is working, thanks!
