### ISSUE TITLE
The fmlrc2 used with racon

### ISSUE THREAD

**Issue by ld9866** [HudsonAlpha/rust-fmlrc#34]
Dear developer:
After we assemble our genome using raven, we want to use fmlrc2 and racon for genome correction, but I am not sure whether to use fmlrc2 or racon first. Can you give me some suggestions?
Best day!

**Comment by holtjma** [comment]
Hello, I don't think we have any full test data to inform the decision. I would defer to published papers that using a multi-correction strategy to determine if one way is better than the other.

**Comment by ld9866** [comment]
OK，Thank you!
