### ISSUE TITLE
Not an Issue ;)

### ISSUE THREAD

**Issue by SimonHegele** [HudsonAlpha/rust-fmlrc#36]
Hello,

I am currently testing various methods for the correction of ONT reads from RNAseq. The quality of the FMLRC2-corrected reads is very decent compared to the other tools I have tested so far. I am not benchmarking the speed but could not not notice that FMLRC2 beats any other Tool by A LOT when it comes to that.
Please don't take "I am going for a coffee because I have to wait for my computations to complete anyways" from us :(
Great tool overall.

Cheers

**Comment by holtjma** [comment]
We'll make a note, maybe fmlrc3 can dispense coffee for you since it doesn't leave time for you to get your own ;)
