### ISSUE TITLE
Correct Nanopore long reads with Pacbio HiFi reads

### ISSUE THREAD

**Issue by Johnsonzcode** [HudsonAlpha/rust-fmlrc#5]
Happy to use fmlrc again and thank you for your excellent work.

Here is the problem : I want to correct Nanopore long reads, but there is no short reads in my data. So Can fmlrc use long reads such as Pacbio HiFi reads to correct Nanopore long reads ? If fmlrc can, how do I set the command parameters ?

Waiting for your reply.

**Comment by holtjma** [comment]
Previously, the thing preventing correction via long reads in FMLRC was the high error rate.  Since PacBio HiFi reads have resolved the majority of this problem, I suspect you could use them to correct against now.  Building the BWT should follow the same process as you would for paired-end short reads, only you will only have one read file.

We haven't tested this (though it's been on my radar for a while now), so I can't say for sure what an optimal (or typically good) set of parameters would be.  Given that HiFi accuracy is quite high now (>99% IIRC) and assuming you have 30x-ish for the HiFi dataset, I would probably just start with the current defaults (k=21,59) for k-mer sizes.  If you're working with diploid or polyploid data, I would also consider lowering the `-m` parameter (but I wouldn't recommend going below 3).  Everything else I would probably leave about the same.  I do recommend using `-C 10` for speed purposes assuming you have a GB of RAM to spare.

If you're open to sharing results, I'm definitely curious to know how it performs in those tests.

**Comment by Johnsonzcode** [comment]
I guess I didi't give enough information to you, my HiFi dataset is about 30X and I am working with diploid. My server can supply up to 250 GB RAM.

**Comment by Johnsonzcode** [comment]
It works , at least it works smoothly but I don't konw how to check the correction quality.

**Comment by holtjma** [comment]
Yea, that really depends on your application, and how you measure "success" in that environment.  I've used [ELECTOR](https://github.com/kamimrcht/ELECTOR) recently, but that was for a simpler non-diploid organism.  I don't think it is built to handle ploidy.  

If you have some sort of "truth set" (such as Genome in a Bottle samples), you could feed the output into variant calling software and test the downstream impact.  If you're doing de novo assembly, then you would probably just be looking at typical de novo stats like N50s, # of contigs, etc.

**Comment by Johnsonzcode** [comment]
That is to say, if I am doing a de novo assembly , I can check the N50s and # of contigs before and after correction to check correction quality, N50s will be longer and # of contigs will be smaller, right ?

**Comment by holtjma** [comment]
In general, yes that's what you're looking for and there are usually other metrics that are less clear cut but informative.  The original FMLRC paper has a [table](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2051-3/tables/4) with a handful of these assembly statistics.  You can probably find a collection of other papers doing assembly or read correction who will have similar statistics.

**Comment by Johnsonzcode** [comment]
How to get error rate ? If I want to know correction quality from N50s and # of contigs , it seems there must be two assembly which are from before and after correction dataset. So if I want to know correction quality directly，“error rate” is a good choice.

**Comment by holtjma** [comment]
[Quast](https://github.com/ablab/quast) is one that I've used in the past that I think it pretty good.  [Quast-LG](http://quast.sourceforge.net/quast-lg.html) and other variants on that page may also be more appropriate.  You will get a bunch of statistics like misassembles, N50, etc.

**Comment by Johnsonzcode** [comment]
Thank you so much !!!

**Comment by Johnsonzcode** [comment]
Sorry to submit again, here is my result.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/S2019/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/S2019/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Supplementary Table 3: Summary of ONT reads |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |   |   |  
Data | ONT reads | Corrected ONT reads*
Length (bp) | Number | Total length (bp) | Percent of length contribution | Number | Total length (bp) | Percent of length contribution
(0, 1,000] | 1,473,294 | 834,389,467 | 0.90% | 1,468,822 | 829,184,902 | 0.88%
(1,000, 5,000] | 2,741,752 | 6,872,969,472 | 7.40% | 2,733,479 | 6,858,785,231 | 7.30%
(5,000, 10,000] | 986,076 | 6,983,491,248 | 7.52% | 988,433 | 7,000,479,384 | 7.45%
(10,000, 15,000] | 460,718 | 5,656,904,073 | 6.09% | 461,426 | 5,665,645,503 | 6.03%
(15,000, 20,000] | 295,748 | 5,131,593,286 | 5.52% | 295,893 | 5,134,214,385 | 5.46%
(20,000, 25,000] | 214,289 | 4,796,891,124 | 5.16% | 214,213 | 4,794,276,889 | 5.10%
(25,000, 30,000] | 200,676 | 5,544,742,388 | 5.97% | 194,001 | 5,353,449,143 | 5.70%
(30,000, 50,000] | 999,836 | 38,325,618,456 | 41.25% | 1,000,911 | 38,507,322,352 | 40.97%
(50,000, 75,000] | 256,267 | 14,981,230,740 | 16.12% | 267,223 | 15,640,703,112 | 16.64%
(75,000, 100,000] | 33,815 | 2,843,289,362 | 3.06% | 36,692 | 3,086,809,520 | 3.28%
(100,000, 150,000] | 7,857 | 887,919,390 | 0.96% | 9,154 | 1,038,055,523 | 1.10%
(150,000, 200,000] | 298 | 49,081,283 | 0.05% | 372 | 61,263,967 | 0.07%
(200,000, 250,000] | 20 | 4,170,809 | 0.00% | 27 | 5,701,347 | 0.01%
(250,000, 300,000] | 5 | 1,361,958 | 0.00% | 5 | 1,380,469 | 0.00%
(300,000, 550,000] | 4 | 1,642,525 | 0.00% | 4 | 1,661,700 | 0.00%
Total | 7,670,655 | 92,915,295,581 | 100.00% | 7,670,655 | 93,978,933,427 | 100.00%
Sequencing depth | 84.47 | 85.44
Total length (Gb) | 92.92 | 93.98
Read N50 (kb) | 34.93 | 34.93
Read number | 7,670,655 | 7,670,655
Mean length (kb) | 12.11 | 12.25
Max length (kb) | 547.66 | 549.75



</body>

</html>
