### ISSUE TITLE
installation (dependency) issue from cargo test --release

### ISSUE THREAD

**Issue by pdimens** [HudsonAlpha/rust-fmlrc#8]
I created a conda environment with `rust` and `cargo` in it and when following the installation instructions I was hit with a dependency error. Is this something you have seen before?
```
> cargo test --release
warning: unused manifest key: package.edition
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: An unknown error occurred

Caused by:
  Feature `std_rng` depends on `rand_hc` which is not an optional dependency.
Consider adding `optional = true` to the dependency

To learn more, run the command again with --verbose.
```

**Comment by holtjma** [comment]
I have not, but this looks like some sort of issue with cargo, the network, or maybe the environment.  Maybe try some of the things in [this thread](https://github.com/rust-lang/cargo/issues/4007) like deleting the registry?

**Comment by pdimens** [comment]
It seems to work with a system-wide rust/cargo install, but not with the directions of the thread, likely because I didn't clear the right registry and couldnt hunt down the alternative. Thanks!
