### ISSUE TITLE
Any plan to include fmlrc2 in Conda?

### ISSUE THREAD

**Issue by fanavarro** [HudsonAlpha/rust-fmlrc#9]
Hi, I am developing different pipelines for genomics, and I would like to use your tool. Normally, I use Conda for managing virtual environments. I have searched your tool in Conda, but there is only the first version. I am wondering if you plan to include this second version in the Conda ecosystem.

Greetings, and thanks for your work!

**Comment by holtjma** [comment]
Hmm, that's a good question.  I didn't have any plans to put it there, but I'm not opposed to it.  I'm not entirely sure how to build a rust package in the Conda ecosystem, so I might have to do some digging when I have spare time.

**Comment by holtjma** [comment]
This should show up sometime soonish.  I'm not sure of how long it takes from PR to release, but here's the PR:
https://github.com/bioconda/bioconda-recipes/pull/26957

**Comment by fanavarro** [comment]
Great, thanks!

I've just seen fmlrc2 in the bioconda webpage, so I'm closing this issue.
